# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [129]:
import numpy as np
import pandas as pd
import requests

# Challenge 1 - Iterators, Generators and `yield`. 

In iterator in Python is an object that represents a stream of data. However, iterators contain a countable number of values. We traverse through the iterator and return one value at a time. All iterators support a `next` function that allows us to traverse through the iterator. We can create an iterator using the `iter` function that comes with the base package of Python. Below is an example of an iterator.

In [5]:
# We first define our iterator:

iterator = iter([1,2,3])

# We can now iterate through the object using the next function

print(next(iterator))

1


In [6]:
# We continue to iterate through the iterator.

print(next(iterator))

2


In [7]:
print(next(iterator))

3


In [8]:
# After we have iterated through all elements, we will get a StopIteration Error

print(next(iterator))

StopIteration: 

In [9]:
# We can also iterate through an iterator using a for loop like this:
# Note: we cannot go back directly in an iterator once we have traversed through the elements. 
# This is why we are redefining the iterator below

iterator = iter([1,2,3])

for i in iterator:
    print(i)

1
2
3


In the cell below, write a function that takes an iterator and returns the first element in the iterator and returns the first element in the iterator that is divisible by 2. Assume that all iterators contain only numeric data. If we have not found a single element that is divisible by 2, return zero.

In [37]:
def divisible_numbers(a_list, a_list_of_terms):
    return [i for i in a_list if all(i%j==0 for j in a_list_of_terms)]

divisible_numbers(range(11), [2])


[0, 2, 4, 6, 8, 10]

### Generators

It is quite difficult to create your own iterator since you would have to implement a `next` function. Generators are functions that enable us to create iterators. The difference between a function and a generator is that instead of using `return`, we use `yield`. For example, below we have a function that returns an iterator containing the numbers 0 through n:

In [41]:
def firstn(n):
     number = 0
     while number < n:
         yield number
         number = number + 1

If we pass 5 to the function, we will see that we have a iterator containing the numbers 0 through 4.

In [42]:
iterator = firstn(5)

for i in iterator:
    print(i)

0
1
2
3
4


In the cell below, create a generator that takes a number and returns an iterator containing all even numbers between 0 and the number you passed to the generator.

In [55]:
p = ( x for x in range(0, 21, 2) )
list(p)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Challenge 2 - Applying Functions to DataFrames

In this challenge, we will look at how to transform cells or entire columns at once.

First, let's load a dataset. We will download the famous Iris classification dataset in the cell below.

In [177]:
columns = ['sepal_length', 'sepal_width', 'petal_length','petal_width','iris_type']
iris = pd.read_csv('iris.csv', names = columns)


Let's look at the dataset using the `head` function.

In [113]:
# Your code here:

iris.head(n=5)

sepal_length  sepal_width  petal_length  petal_width    iris_type
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Let's start off by using built-in functions. Try to apply the numpy mean function and describe what happens in the comments of the code.

In [141]:
# Your code here:

print("The Average Sepal lenght is {}.".format(iris.sepal_length.mean()))
print("The Average Sepal width is {}.".format(iris.sepal_width.mean()))
print("The Average Petal lenght is {}.".format(iris.petal_length.mean()))
print("The Average Petal width is {}.".format(iris.petal_width.mean()))



The Average Sepal lenght is 5.843333333333335.
The Average Sepal width is 3.0540000000000007.
The Average Petal lenght is 3.7586666666666693.
The Average Petal width is 1.1986666666666672.


Next, we'll apply the standard deviation function in numpy (`np.std`). Describe what happened in the comments.

In [143]:
# Your code here:

print("The Standard Deviation in Sepal lenght is {}.".format(iris.sepal_length.std()))
print("The Standard Deviation in Sepal width is {}.".format(iris.sepal_width.std()))
print("The Standard Deviation in Petal lenght is {}.".format(iris.petal_length.std()))
print("The Standard Deviation in Petal width is {}.".format(iris.petal_width.std()))

The Standard Deviation in Sepal lenght is 0.8280661279778629.
The Standard Deviation in Sepal width is 0.4335943113621737.
The Standard Deviation in Petal lenght is 1.7644204199522617.
The Standard Deviation in Petal width is 0.7631607417008414.


The measurements are in centimeters. Let's convert them all to inches. First, we will create a dataframe that contains only the numeric columns. Assign this new dataframe to `iris_numeric`.

In [157]:
# Your code here:
iris_numerics = iris[['sepal_length','sepal_width','petal_length','petal_width']]
print(iris_numerics)

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


Next, we will write a function that converts centimeters to inches in the cell below. Recall that 1cm = 0.393701in.

In [159]:
def cm_to_in(x):
    # This function takes in a numeric value in centimeters and converts it to inches
    # Input: numeric value
    # Output: float
    
    # Sample Input: 1.0
    # Sample Output: 0.393701
    
    # Your code here:
    inch = 0.393701
    return x*inch

Now convert all columns in `iris_numeric` to inches in the cell below. We like to think of functional transformations as immutable. Therefore, save the transformed data in a dataframe called `iris_inch`.

In [161]:
# Your code here:

iris_inch = np.apply_along_axis(cm_to_in, axis=0, arr=iris_numerics)

print(iris_inch)

[[2.0078751 1.3779535 0.5511814 0.0787402]
 [1.9291349 1.181103  0.5511814 0.0787402]
 [1.8503947 1.2598432 0.5118113 0.0787402]
 [1.8110246 1.2204731 0.5905515 0.0787402]
 [1.968505  1.4173236 0.5511814 0.0787402]
 [2.1259854 1.5354339 0.6692917 0.1574804]
 [1.8110246 1.3385834 0.5511814 0.1181103]
 [1.968505  1.3385834 0.5905515 0.0787402]
 [1.7322844 1.1417329 0.5511814 0.0787402]
 [1.9291349 1.2204731 0.5905515 0.0393701]
 [2.1259854 1.4566937 0.5905515 0.0787402]
 [1.8897648 1.3385834 0.6299216 0.0787402]
 [1.8897648 1.181103  0.5511814 0.0393701]
 [1.6929143 1.181103  0.4330711 0.0393701]
 [2.2834658 1.574804  0.4724412 0.0787402]
 [2.2440957 1.7322844 0.5905515 0.1574804]
 [2.1259854 1.5354339 0.5118113 0.1574804]
 [2.0078751 1.3779535 0.5511814 0.1181103]
 [2.2440957 1.4960638 0.6692917 0.1181103]
 [2.0078751 1.4960638 0.5905515 0.1181103]
 [2.1259854 1.3385834 0.6692917 0.0787402]
 [2.0078751 1.4566937 0.5905515 0.1574804]
 [1.8110246 1.4173236 0.393701  0.0787402]
 [2.0078751

We have just found that the original measurements were off by a constant. Define the global constant `error` and set it to 2. Write a function that uses the global constant and adds it to each cell in the dataframe. Apply this function to `iris_numeric` and save the result in `iris_constant`.

In [162]:
# Define constant below:
constant = 2

def add_constant(x):
    # This function adds a global constant to our input.
    # Input: numeric value
    # Output: numeric value
    
    # Your code here:
    return x + constant

iris_constant = np.apply_along_axis(add_constant, axis=0, arr=iris_numerics)

print(iris_constant)

[[7.1 5.5 3.4 2.2]
 [6.9 5.  3.4 2.2]
 [6.7 5.2 3.3 2.2]
 [6.6 5.1 3.5 2.2]
 [7.  5.6 3.4 2.2]
 [7.4 5.9 3.7 2.4]
 [6.6 5.4 3.4 2.3]
 [7.  5.4 3.5 2.2]
 [6.4 4.9 3.4 2.2]
 [6.9 5.1 3.5 2.1]
 [7.4 5.7 3.5 2.2]
 [6.8 5.4 3.6 2.2]
 [6.8 5.  3.4 2.1]
 [6.3 5.  3.1 2.1]
 [7.8 6.  3.2 2.2]
 [7.7 6.4 3.5 2.4]
 [7.4 5.9 3.3 2.4]
 [7.1 5.5 3.4 2.3]
 [7.7 5.8 3.7 2.3]
 [7.1 5.8 3.5 2.3]
 [7.4 5.4 3.7 2.2]
 [7.1 5.7 3.5 2.4]
 [6.6 5.6 3.  2.2]
 [7.1 5.3 3.7 2.5]
 [6.8 5.4 3.9 2.2]
 [7.  5.  3.6 2.2]
 [7.  5.4 3.6 2.4]
 [7.2 5.5 3.5 2.2]
 [7.2 5.4 3.4 2.2]
 [6.7 5.2 3.6 2.2]
 [6.8 5.1 3.6 2.2]
 [7.4 5.4 3.5 2.4]
 [7.2 6.1 3.5 2.1]
 [7.5 6.2 3.4 2.2]
 [6.9 5.1 3.5 2.1]
 [7.  5.2 3.2 2.2]
 [7.5 5.5 3.3 2.2]
 [6.9 5.1 3.5 2.1]
 [6.4 5.  3.3 2.2]
 [7.1 5.4 3.5 2.2]
 [7.  5.5 3.3 2.3]
 [6.5 4.3 3.3 2.3]
 [6.4 5.2 3.3 2.2]
 [7.  5.5 3.6 2.6]
 [7.1 5.8 3.9 2.4]
 [6.8 5.  3.4 2.3]
 [7.1 5.8 3.6 2.2]
 [6.6 5.2 3.4 2.2]
 [7.3 5.7 3.5 2.2]
 [7.  5.3 3.4 2.2]
 [9.  5.2 6.7 3.4]
 [8.4 5.2 6.5 3.5]
 [8.9 5.1 6.

# Bonus Challenge - Applying Functions to Columns

Read more about applying functions to either rows or columns [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.apply.html) and write a function that computes the maximum value for each row of `iris_numeric`

In [183]:
# Your code here:

max_value_by_row = iris_numerics.max(axis = 1)

print(max_value_by_row)

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Length: 150, dtype: float64


Compute the combined lengths for each row and the combined widths for each row using a function. Assign these values to new columns `total_length` and `total_width`.

In [194]:
# Your code here:

total_length = iris_numerics[columns[0]] + iris_numerics[columns[2]]
total_width = iris_numerics[columns[1]] + iris_numerics[columns[3]]

print(total_length,total_width)

0       6.5
1       6.3
2       6.0
3       6.1
4       6.4
       ... 
145    11.9
146    11.3
147    11.7
148    11.6
149    11.0
Length: 150, dtype: float64 0      3.7
1      3.2
2      3.4
3      3.3
4      3.8
      ... 
145    5.3
146    4.4
147    5.0
148    5.7
149    4.8
Length: 150, dtype: float64
